"""003_add_discovery_templates_usage

Revision ID: 960ccc1ed031
Revises: 002_align_fields
Create Date: 2026-06-26 02:13:10.512654
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '960ccc1ed031'
down_revision: Union[str, None] = '002_align_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_templates',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_brand', sa.String(length=255), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('source_plan', postgresql.JSONB(), nullable=False),
    sa.Column('run_plan', postgresql.JSONB(), nullable=False),
    sa.Column('feishu_sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_templates_name'), 'collection_templates', ['name'], unique=False)
    op.create_index(op.f('ix_collection_templates_status'), 'collection_templates', ['status'], unique=False)
    op.create_table('discovery_sessions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('query', sa.String(length=1024), nullable=False),
    sa.Column('target_brand', sa.String(length=255), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('model_provider', sa.String(length=64), nullable=True),
    sa.Column('search_provider', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovery_sessions_query'), 'discovery_sessions', ['query'], unique=False)
    op.create_index(op.f('ix_discovery_sessions_status'), 'discovery_sessions', ['status'], unique=False)
    op.create_table('usage_daily_stats',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('task_count', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('search_count', sa.Integer(), nullable=False),
    sa.Column('collected_page_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('raw_metadata', postgresql.JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_daily_stats_stat_date'), 'usage_daily_stats', ['stat_date'], unique=True)
    op.create_table('scheduled_collections',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('template_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('schedule_type', sa.String(length=16), nullable=False),
    sa.Column('cron_expr', sa.String(length=128), nullable=True),
    sa.Column('interval_minutes', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=32), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('max_failures_before_pause', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['collection_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_collections_template_id'), 'scheduled_collections', ['template_id'], unique=False)
    op.create_table('source_candidates',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('discovery_session_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=2048), nullable=True),
    sa.Column('favicon_url', sa.String(length=2048), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('recommended_collector', sa.String(length=32), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('raw_metadata', postgresql.JSONB(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['discovery_session_id'], ['discovery_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_candidates_discovery_session_id'), 'source_candidates', ['discovery_session_id'], unique=False)
    op.create_index(op.f('ix_source_candidates_domain'), 'source_candidates', ['domain'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_candidates_domain'), table_name='source_candidates')
    op.drop_index(op.f('ix_source_candidates_discovery_session_id'), table_name='source_candidates')
    op.drop_table('source_candidates')
    op.drop_index(op.f('ix_scheduled_collections_template_id'), table_name='scheduled_collections')
    op.drop_table('scheduled_collections')
    op.drop_index(op.f('ix_usage_daily_stats_stat_date'), table_name='usage_daily_stats')
    op.drop_table('usage_daily_stats')
    op.drop_index(op.f('ix_discovery_sessions_status'), table_name='discovery_sessions')
    op.drop_index(op.f('ix_discovery_sessions_query'), table_name='discovery_sessions')
    op.drop_table('discovery_sessions')
    op.drop_index(op.f('ix_collection_templates_status'), table_name='collection_templates')
    op.drop_index(op.f('ix_collection_templates_name'), table_name='collection_templates')
    op.drop_table('collection_templates')
    # ### end Alembic commands ###
